---
# tasks file for ansible-role-docker-registry
- name: Container present
  docker_container:
    name: registry
    state: present
    image: registry:2
    restart: yes
    detach: true
    ports:
      - "5000:5000"
